// @ 后面指定版本分支
@Library("ShareLibrary-Jenkins@main") _

def build = new org.library.build()
def deploy = new org.library.deploy()

String buildShell = "${env.buildShell}"
String buildType = "${env.buildType}"
String gitlab_url = "${env.gitlab_url}"
String branchName = "${env.branchName}"

pipeline {
    agent {
        node {
            label "build-1"
        }
    }
    
    stages{
        stage("CheckOut") {
            steps {
                // credentialsId 为你的Jenkins credentials 中添加的凭证
                script{
                    checkout([$class: 'GitSCM', branches: [[name: "${branchName}"]], extensions: [], userRemoteConfigs: [[credentialsId: 'github_pass', url: "${gitlab_url}"]]])
                }
            }
        }
        stage("Build") {
            steps {
                script{
                    build.Build(buildType, buildShell)
                }
            }
        }
    }
}